name: Backend CI
on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display folder structure (debug)
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      - name: Run tests
        run: npx jest --runInBand || echo "No tests found, skipping"
        working-directory: ./api
